// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Inicio de sesion', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Inicio de sesion', async function() {
    await driver.get("https://buggy.justtestit.org/")
    await driver.manage().window().setRect({ width: 968, height: 962 })
    await driver.findElement(By.name("login")).click()
    await driver.findElement(By.name("login")).sendKeys("testing@coches.com")
    await driver.findElement(By.name("password")).click()
    await driver.findElement(By.name("password")).sendKeys("1234567rR&")
    await driver.findElement(By.css(".btn-success")).click()
    await driver.findElement(By.linkText("Logout")).click()
  })
})
