// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('pruebas exploratorias pantalla completa_Damian', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('pruebas exploratorias pantalla completa_Damian', async function() {
    await driver.get("https://damiansebastians.github.io/OXYGENShop-Project/")
    await driver.manage().window().setRect({ width: 1936, height: 1056 })
    await driver.findElement(By.css(".title-button > p")).click()
    await driver.findElement(By.linkText("BENEFITS")).click()
    await driver.findElement(By.linkText("PRICES")).click()
    await driver.findElement(By.css("#menu-items > li:nth-child(4)")).click()
    await driver.findElement(By.linkText("CONTACT")).click()
    await driver.findElement(By.linkText("WHY US")).click()
    await driver.findElement(By.css(".header-text")).click()
    await driver.findElement(By.id("currency-select")).click()
    {
      const dropdown = await driver.findElement(By.id("currency-select"))
      await dropdown.findElement(By.xpath("//option[. = 'USD']")).click()
    }
    await driver.findElement(By.id("currency-select")).click()
    {
      const dropdown = await driver.findElement(By.id("currency-select"))
      await dropdown.findElement(By.xpath("//option[. = 'GBP']")).click()
    }
    await driver.findElement(By.id("currency-select")).click()
    {
      const dropdown = await driver.findElement(By.id("currency-select"))
      await dropdown.findElement(By.xpath("//option[. = 'EUR']")).click()
    }
    await driver.findElement(By.css(".next-btn")).click()
    await driver.findElement(By.css(".next-btn")).click()
    await driver.findElement(By.css(".next-btn")).click()
    await driver.findElement(By.css(".next-btn")).click()
    await driver.findElement(By.css(".prev-btn")).click()
    await driver.findElement(By.css(".prev-btn")).click()
    await driver.findElement(By.css(".prev-btn")).click()
    await driver.findElement(By.id("name")).click()
    await driver.findElement(By.id("name")).sendKeys("zolee1")
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("certe@test.com")
    await driver.findElement(By.id("button-send")).click()
    await driver.findElement(By.id("consent")).click()
    await driver.findElement(By.id("button-send")).click()
    await driver.findElement(By.id("return-top")).click()
  })
})
